<?php

namespace Database\Seeders;

use App\Models\AuditLog;
use App\Models\User;
use Illuminate\Database\Seeder;

class AuditLogSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::where('email', 'admin@supdata.com')->first();

        if (!$admin) {
            return;
        }

        $logs = [
            [
                'user_id' => $admin->id,
                'action' => 'Création',
                'module' => 'Utilisateurs',
                'description' => 'Création de l\'utilisateur Ahmed Tazi',
                'target' => 'Ahmed Tazi',
                'status' => 'Succès',
                'ip_address' => '192.168.1.42',
                'user_agent' => 'Chrome — Windows 11',
                'old_values' => null,
                'new_values' => ['nom' => 'Ahmed Tazi', 'email' => 'ahmed.tazi@supdata.ma', 'role' => 'Responsable Stock'],
                'created_at' => now()->subDays(5)->setTime(9, 45, 12),
            ],
            [
                'user_id' => $admin->id,
                'action' => 'Création',
                'module' => 'Agences',
                'description' => 'Création de l\'agence SUPDATA Tanger',
                'target' => 'SUPDATA Tanger',
                'status' => 'Succès',
                'ip_address' => '192.168.1.10',
                'user_agent' => 'Chrome — Windows 11',
                'old_values' => null,
                'new_values' => ['nom' => 'SUPDATA Tanger', 'ville' => 'Tanger', 'adresse' => '12 Rue Mohammed V'],
                'created_at' => now()->subDays(5)->setTime(9, 30, 5),
            ],
            [
                'user_id' => $admin->id,
                'action' => 'Modification',
                'module' => 'Rôles',
                'description' => 'Modification des permissions du rôle Gestionnaire',
                'target' => 'Gestionnaire',
                'status' => 'Succès',
                'ip_address' => '192.168.1.10',
                'user_agent' => 'Chrome — Windows 11',
                'old_values' => ['permissions' => 10],
                'new_values' => ['permissions' => 13],
                'created_at' => now()->subDays(5)->setTime(9, 15, 33),
            ],
            [
                'user_id' => $admin->id,
                'action' => 'Connexion',
                'module' => 'Système',
                'description' => 'Connexion au système',
                'target' => null,
                'status' => 'Succès',
                'ip_address' => '192.168.1.10',
                'user_agent' => 'Chrome — Windows 11',
                'old_values' => null,
                'new_values' => null,
                'created_at' => now()->subDays(5)->setTime(8, 15, 0),
            ],
            [
                'user_id' => $admin->id,
                'action' => 'Suppression',
                'module' => 'Utilisateurs',
                'description' => 'Suppression de l\'utilisateur test@supdata.ma',
                'target' => 'test@supdata.ma',
                'status' => 'Succès',
                'ip_address' => '192.168.1.10',
                'user_agent' => 'Chrome — Windows 11',
                'old_values' => ['nom' => 'Test User', 'role' => 'Utilisateur'],
                'new_values' => null,
                'created_at' => now()->subDays(4)->setTime(17, 45, 10),
            ],
            [
                'user_id' => $admin->id,
                'action' => 'Modification',
                'module' => 'Paramètres',
                'description' => 'Activation du mode maintenance',
                'target' => 'Mode maintenance',
                'status' => 'Succès',
                'ip_address' => '192.168.1.10',
                'user_agent' => 'Chrome — Windows 11',
                'old_values' => ['actif' => false],
                'new_values' => ['actif' => true],
                'created_at' => now()->subDays(4)->setTime(15, 0, 0),
            ],
            [
                'user_id' => $admin->id,
                'action' => 'Création',
                'module' => 'Utilisateurs',
                'description' => 'Création de l\'utilisateur Fatima Zahra Benani',
                'target' => 'Fatima Zahra Benani',
                'status' => 'Succès',
                'ip_address' => '192.168.1.42',
                'user_agent' => 'Chrome — Windows 11',
                'old_values' => null,
                'new_values' => ['nom' => 'Fatima Zahra Benani', 'email' => 'fatima.zahra@supdata.ma', 'role' => 'Responsable Stock'],
                'created_at' => now()->subDays(4)->setTime(15, 30, 20),
            ],
            [
                'user_id' => $admin->id,
                'action' => 'Modification',
                'module' => 'Paramètres',
                'description' => 'Mise à jour du nom de la plateforme',
                'target' => 'Nom de la plateforme',
                'status' => 'Succès',
                'ip_address' => '192.168.1.10',
                'user_agent' => 'Chrome — Windows 11',
                'old_values' => ['valeur' => 'SUPDATA ERP'],
                'new_values' => ['valeur' => 'SUPDATA ERP v2'],
                'created_at' => now()->subDays(3)->setTime(17, 0, 10),
            ],
            [
                'user_id' => $admin->id,
                'action' => 'Création',
                'module' => 'Utilisateurs',
                'description' => 'Création de l\'utilisateur Rachid Mouline',
                'target' => 'Rachid Mouline',
                'status' => 'Succès',
                'ip_address' => '192.168.1.88',
                'user_agent' => 'Edge — Windows 11',
                'old_values' => null,
                'new_values' => ['nom' => 'Rachid Mouline', 'email' => 'rachid.mouline@supdata.ma', 'role' => 'Administrateur Local'],
                'created_at' => now()->subDays(3)->setTime(13, 0, 30),
            ],
            [
                'user_id' => $admin->id,
                'action' => 'Suppression',
                'module' => 'Agences',
                'description' => 'Suppression de l\'agence SUPDATA Test',
                'target' => 'SUPDATA Test',
                'status' => 'Succès',
                'ip_address' => '192.168.1.10',
                'user_agent' => 'Chrome — Windows 11',
                'old_values' => ['ville' => 'Testville', 'statut' => 'Inactif'],
                'new_values' => null,
                'created_at' => now()->subDays(3)->setTime(14, 0, 20),
            ],
            [
                'user_id' => $admin->id,
                'action' => 'Modification',
                'module' => 'Rôles',
                'description' => 'Création du nouveau rôle Responsable Stock',
                'target' => 'Responsable Stock',
                'status' => 'Succès',
                'ip_address' => '192.168.1.10',
                'user_agent' => 'Chrome — Windows 11',
                'old_values' => null,
                'new_values' => ['permissions' => 8, 'description' => 'Gestion du stock et des mouvements'],
                'created_at' => now()->subDays(2)->setTime(14, 30, 0),
            ],
            [
                'user_id' => $admin->id,
                'action' => 'Modification',
                'module' => 'Paramètres',
                'description' => 'Ajout d\'un nouveau paramètre de notification',
                'target' => 'Notifications email',
                'status' => 'Succès',
                'ip_address' => '192.168.1.88',
                'user_agent' => 'Edge — Windows 11',
                'old_values' => null,
                'new_values' => ['clé' => 'email_notifications', 'valeur' => 'true'],
                'created_at' => now()->subDays(2)->setTime(16, 0, 0),
            ],
            [
                'user_id' => $admin->id,
                'action' => 'Création',
                'module' => 'Utilisateurs',
                'description' => 'Création de l\'utilisateur Sara Filali',
                'target' => 'Sara Filali',
                'status' => 'Succès',
                'ip_address' => '172.16.0.44',
                'user_agent' => 'Chrome — Windows 11',
                'old_values' => null,
                'new_values' => ['nom' => 'Sara Filali', 'email' => 'sara.filali@supdata.ma', 'role' => 'Responsable Commercial'],
                'created_at' => now()->subDays(1)->setTime(16, 30, 20),
            ],
            [
                'user_id' => $admin->id,
                'action' => 'Connexion',
                'module' => 'Système',
                'description' => 'Connexion au système',
                'target' => null,
                'status' => 'Succès',
                'ip_address' => '192.168.2.22',
                'user_agent' => 'Chrome — macOS',
                'old_values' => null,
                'new_values' => null,
                'created_at' => now()->subDays(1)->setTime(13, 30, 45),
            ],
            [
                'user_id' => $admin->id,
                'action' => 'Export',
                'module' => 'Utilisateurs',
                'description' => 'Export de la liste des utilisateurs',
                'target' => 'Liste utilisateurs',
                'status' => 'Succès',
                'ip_address' => '192.168.1.88',
                'user_agent' => 'Edge — Windows 11',
                'old_values' => null,
                'new_values' => ['format' => 'CSV', 'lignes' => 48],
                'created_at' => now()->subDay()->setTime(16, 30, 20),
            ],
        ];

        foreach ($logs as $log) {
            AuditLog::create($log);
        }
    }
}
