import { useState } from "react";
import { Link } from "@inertiajs/react";
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertCircle, ArrowRight, CheckCircle2, Clock3, FileCheck2, FilePlus2, Search, ShieldCheck, XCircle } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/Components/UI/Card";
import { Badge } from "@/Components/UI/Badge";
import { Button } from "@/Components/UI/Button";
import { Input } from "@/Components/UI/Input";
import { Textarea } from "@/Components/UI/Textarea";
import { DataTable } from "@/Components/UI/DataTable";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/Components/UI/Dialog";
import { useToast } from "@/Components/UI/Toast";

const icons = [FileCheck2, ShieldCheck, FilePlus2, CheckCircle2, XCircle, Clock3];
const tones = { amber: "bg-amber-50 text-amber-700", blue: "bg-blue-50 text-blue-700", violet: "bg-violet-50 text-violet-700", emerald: "bg-emerald-50 text-emerald-700", red: "bg-red-50 text-red-700", cyan: "bg-cyan-50 text-cyan-700" };
const Info = ({ label, value }) => <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-sm font-semibold text-slate-800">{value}</p></div>;

export default function AdministrativeWorkspace({ dashboard }) {
    const toast = useToast();
    const [selected, setSelected] = useState(null);
    const [decision, setDecision] = useState("");
    const [reason, setReason] = useState("");
    const close = () => { setSelected(null); setDecision(""); setReason(""); };
    const canProcess = selected && !["Validée et transmise", "Rejetée"].includes(selected.status);
    const submit = () => {
        const result = dashboard.updateRequest(selected.id, decision, reason.trim());
        if (!result.ok) return toast(result.message, "error");
        toast(decision === "Validée" ? "Demande validée et transmise à l’Administrateur Local." : "Demande rejetée et Responsable Commercial informé.", decision === "Validée" ? "success" : "warning");
        close();
    };
    const columns = [
        { header: "Référence", accessorKey: "id", className: "font-semibold text-slate-900" },
        { header: "Demandeur / Client", cell: r => <div><p className="font-medium">{r.requester}</p><p className="text-xs text-slate-500">{r.client}</p></div> },
        { header: "Agence", accessorKey: "agency" }, { header: "Montant", accessorKey: "amount" },
        { header: "Complétude", cell: r => <div className="w-24"><div className="h-1.5 rounded-full bg-slate-100"><div className={`h-1.5 rounded-full ${r.completeness === 100 ? "bg-emerald-500" : "bg-amber-500"}`} style={{ width: `${r.completeness}%` }}/></div><span className="text-xs text-slate-500">{r.completeness} %</span></div> },
        { header: "Statut", cell: r => <Badge variant={r.status === "Informations manquantes" ? "warning" : r.status === "Rejetée" ? "destructive" : r.status === "Validée et transmise" ? "success" : "secondary"}>{r.status}</Badge> },
        { header: "Action", cell: r => <Button size="sm" variant="outline" onClick={() => setSelected(r)}>{["Validée et transmise", "Rejetée"].includes(r.status) ? "Consulter" : "Vérifier"} <ArrowRight className="size-3.5"/></Button> },
    ];
    return <div className="flex flex-col gap-6">
        <Dialog open={Boolean(selected)} onOpenChange={open => !open && close()}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Vérification de {selected?.id}</DialogTitle><DialogDescription>Contrôlez le dossier puis choisissez une décision.</DialogDescription></DialogHeader>{selected && <div className="grid gap-3 sm:grid-cols-2"><Info label="Demandeur" value={selected.requester}/><Info label="Client" value={selected.client}/><Info label="Agence" value={selected.agency}/><Info label="Montant" value={selected.amount}/><Info label="Produits" value={selected.products}/><Info label="Complétude" value={`${selected.completeness} %`}/></div>}{canProcess && <div><p className="mb-2 text-sm font-medium">Décision</p><div className="flex flex-wrap gap-2"><Button variant={decision === "Validée" ? "default" : "outline"} onClick={() => setDecision("Validée")} disabled={selected.completeness !== 100}><CheckCircle2 className="size-4"/>Valider et transmettre</Button><Button variant={decision === "Rejetée" ? "destructive" : "outline"} onClick={() => setDecision("Rejetée")}><XCircle className="size-4"/>Rejeter</Button></div>{selected.completeness !== 100 && <p className="mt-2 text-xs font-medium text-amber-700">Validation bloquée : les informations sont incomplètes.</p>}</div>}{canProcess && decision === "Rejetée" && <Textarea value={reason} onChange={e => setReason(e.target.value)} placeholder="Motif obligatoire du rejet…" aria-label="Motif du rejet" aria-required="true"/>}<DialogFooter><Button variant="ghost" onClick={close}>Fermer</Button>{canProcess && <Button disabled={!decision} onClick={submit}>Confirmer</Button>}</DialogFooter></DialogContent></Dialog>
        <section className="border-b-2 border-slate-900 pb-5"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-blue-700">Gestion administrative · Poste de contrôle</p><h1 className="mt-2 text-2xl font-semibold tracking-tight text-slate-950">Demandes et validations internes</h1><p className="mt-2 text-sm text-slate-500">{dashboard.user.name} · Toutes les agences · Mise à jour aujourd’hui</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => document.getElementById("demandes-acceptees")?.scrollIntoView({behavior:"smooth"})}>Demandes acceptées</Button><Button onClick={() => document.getElementById("verification")?.scrollIntoView({behavior:"smooth"})}>Ouvrir la file</Button></div></div></section>
        <section className="overflow-hidden rounded-lg border border-slate-300 bg-white"><div className="grid divide-y divide-slate-200 sm:grid-cols-2 sm:divide-x sm:divide-y-0 xl:grid-cols-6">{dashboard.stats.map((item,i) => { const Icon=icons[i]; return <div key={item.id} className="min-w-0 p-4"><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{item.label}</span><Icon className="size-4 text-slate-400"/></div><p className="mt-3 font-mono text-2xl font-semibold tabular-nums text-slate-950">{item.value}</p><p className="mt-1 truncate text-xs text-slate-500">{item.detail}</p></div>})}</div></section>
        <Card id="verification" className="rounded-lg border-slate-300 shadow-none"><CardHeader><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-blue-700">Travail prioritaire</p><CardTitle className="mt-1">File de vérification</CardTitle><p className="mt-1 text-sm text-slate-500">Demandes reçues du Responsable Commercial</p></div><div className="flex gap-2"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><Input value={dashboard.query} onChange={e=>dashboard.setQuery(e.target.value)} placeholder="Rechercher…" className="pl-9"/></div><select value={dashboard.agency} onChange={e=>dashboard.setAgency(e.target.value)} className="rounded-md border px-3 text-sm"><option>Toutes</option><option>Casablanca</option><option>Marrakech</option></select></div></div></CardHeader><CardContent><DataTable columns={columns} data={dashboard.requests} emptyMessage="Aucune demande à traiter."/></CardContent></Card>
        <div className="grid gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader><CardTitle>Volume de traitement</CardTitle></CardHeader><CardContent><div className="h-64"><ResponsiveContainer><AreaChart data={dashboard.trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="week"/><YAxis/><Tooltip/><Area dataKey="recues" name="Reçues" stroke="#94a3b8" fill="transparent"/><Area dataKey="traitees" name="Traitées" stroke="#2563eb" fill="#dbeafe"/></AreaChart></ResponsiveContainer></div></CardContent></Card><Card><CardHeader><CardTitle>État du flux mensuel</CardTitle></CardHeader><CardContent><div className="h-64"><ResponsiveContainer><PieChart><Pie data={dashboard.flow} dataKey="value" nameKey="label" innerRadius={58} outerRadius={85}>{dashboard.flow.map(e=><Cell key={e.label} fill={e.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div></CardContent></Card></div>
        <div className="grid gap-4 lg:grid-cols-3"><Card id="demandes-acceptees" className="lg:col-span-2"><CardHeader><CardTitle>Validations finales reçues</CardTitle></CardHeader><CardContent><div className="flex flex-col gap-3">{dashboard.approvedRequests.map(o=><div key={o.id} className="flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center"><div className="flex-1"><p className="font-semibold">{o.id} · {o.requester}</p><p className="text-sm text-slate-500">{o.agency} · {o.amount}</p></div><Badge variant="success">Validation finale</Badge><Button size="sm" asChild><Link href="/dashboard-administrative/demandes-acceptees">Consulter</Link></Button></div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>Points d’attention</CardTitle></CardHeader><CardContent><div className="flex flex-col gap-4">{dashboard.notifications.map(n=><div key={n.id} className="flex gap-3"><AlertCircle className="mt-1 size-4 shrink-0 text-amber-600"/><div><p className="text-sm font-semibold">{n.title}</p><p className="text-xs leading-5 text-slate-500">{n.text}</p></div></div>)}</div><Button variant="ghost" className="mt-4 w-full" onClick={()=>{dashboard.resetDashboard();toast("Données de démonstration réinitialisées.","info")}}>Réinitialiser la démonstration</Button></CardContent></Card></div>
    </div>;
}
