import { useState } from "react";
import { Edit3, Eye, Plus, RotateCcw, Search, Trash2 } from "lucide-react";
import { Badge } from "@/Components/UI/Badge";
import { Button } from "@/Components/UI/Button";
import { Card, CardContent, CardHeader, CardTitle } from "@/Components/UI/Card";
import { DataTable } from "@/Components/UI/DataTable";
import { Input } from "@/Components/UI/Input";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/Components/UI/Dialog";
import { useToast } from "@/Components/UI/Toast";
import StockOperationForm from "./StockOperationForm";

const empty = { nom:"", detail:"", agence:"Casablanca", quantite:"", type:"Entrée" };
const warning = ["Stock faible","À contrôler","À valider","À confirmer","En transit","En cours","En préparation"];
const status = value => <Badge variant={["Rupture","Critique"].includes(value)?"destructive":warning.includes(value)?"warning":"success"}>{value}</Badge>;

export default function StockOperationsPanel({ operations }) {
 const toast=useToast(); const [formOpen,setFormOpen]=useState(false); const [editing,setEditing]=useState(null); const [selected,setSelected]=useState(null); const [form,setForm]=useState(empty);
 const create=()=>{setEditing(null);setForm(empty);setFormOpen(true)};
 const edit=i=>{setEditing(i);setForm({nom:i.nom,detail:i.detail||"",agence:i.agence,quantite:i.quantite,type:i.type||"Entrée"});setFormOpen(true)};
 const submit=()=>{if(!form.nom||form.quantite===""||Number(form.quantite)<0||(operations.section==="inventaires"&&Number(form.quantite)>100))return toast("Vérifiez les informations saisies.","error"); editing?operations.updateItem(editing.id,form):operations.createItem(form);setFormOpen(false);toast(editing?"Élément modifié.":"Élément créé.")};
 const transition=i=>{operations.transitionItem(i.id);toast(operations.section==="receptions"?"Réception contrôlée et validée.":operations.section==="livraisons"?"Remise au client confirmée.":"Alerte traitée.")};
 const actions=i=><div className="flex justify-end gap-2"><Button size="sm" variant="ghost" onClick={()=>setSelected(i)} aria-label={`Consulter ${i.nom}`}><Eye className="size-3.5"/></Button>{operations.config.workflow&&operations.canTransition(i)&&<Button size="sm" onClick={()=>transition(i)}>{operations.section==="receptions"?"Valider":operations.section==="livraisons"?"Confirmer":"Traiter"}</Button>}{operations.config.canCrud&&<><Button size="sm" variant="outline" onClick={()=>edit(i)}><Edit3 className="size-3.5"/></Button><Button size="sm" variant="ghost" className="text-red-600" onClick={()=>operations.deleteItem(i.id)}><Trash2 className="size-3.5"/></Button></>}</div>;
 const ref={header:"Référence",accessorKey:"id",className:"font-mono text-xs font-semibold"};
 const columnsBySection={
  mouvements:[ref,{header:"Sens",cell:i=><Badge variant={(i.type||i.nom)?.toLowerCase().includes("sortie")?"warning":"success"}>{i.type||i.nom?.split("·")[0]||"Mouvement"}</Badge>},{header:"Produit / motif",cell:i=><div><p className="font-medium">{i.type?i.nom:(i.nom?.split("·").slice(1).join("·")||i.nom)}</p><p className="text-xs text-slate-500">{i.detail}</p></div>},{header:"Agence",accessorKey:"agence"},{header:"Quantité",cell:i=><b className="font-mono">{i.quantite}</b>},{header:"Traçabilité",cell:i=>status(i.statut)},{header:"Actions",cell:actions,className:"text-right"}],
  receptions:[ref,{header:"Fournisseur",accessorKey:"nom"},{header:"BL / marchandises",accessorKey:"detail"},{header:"Agence d’arrivée",accessorKey:"agence"},{header:"Reçu",cell:i=><b className="font-mono">{i.quantite} unités</b>},{header:"Contrôle",cell:i=>status(i.statut)},{header:"Actions",cell:actions,className:"text-right"}],
  inventaires:[ref,{header:"Campagne",accessorKey:"nom"},{header:"Périmètre / écarts",accessorKey:"detail"},{header:"Agence",accessorKey:"agence"},{header:"Avancement",cell:i=><div className="min-w-28"><div className="mb-1 flex justify-between text-xs"><span>Comptage</span><span>{i.quantite}%</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-emerald-500" style={{width:`${Math.min(100,i.quantite)}%`}}/></div></div>},{header:"État",cell:i=>status(i.statut)},{header:"Actions",cell:actions,className:"text-right"}],
  livraisons:[ref,{header:"Client / destination",accessorKey:"nom"},{header:"Marchandises",accessorKey:"detail"},{header:"Agence d’expédition",accessorKey:"agence"},{header:"À livrer",cell:i=><b className="font-mono">{i.quantite} unités</b>},{header:"Acheminement",cell:i=>status(i.statut)},{header:"Actions",cell:actions,className:"text-right"}],
 };
 const generic=[ref,{header:"Élément",cell:i=><div><p className="font-medium">{i.nom}</p><p className="text-xs text-slate-500">{i.detail}</p></div>},{header:"Agence",accessorKey:"agence"},{header:"Quantité",accessorKey:"quantite"},{header:"Statut",cell:i=>status(i.statut)},{header:"Actions",cell:actions,className:"text-right"}];
 const columns=columnsBySection[operations.section]||generic;
 return <>
  <Dialog open={Boolean(selected)} onOpenChange={o=>!o&&setSelected(null)}><DialogContent><DialogHeader><DialogTitle>{operations.config.titre} · {selected?.id}</DialogTitle><DialogDescription>Détail opérationnel</DialogDescription></DialogHeader>{selected&&<div className="grid gap-3 sm:grid-cols-2">{Object.entries({Élément:selected.nom,Détail:selected.detail,Agence:selected.agence,Quantité:selected.quantite,Statut:selected.statut}).map(([k,v])=><div key={k} className="rounded-lg border p-3"><p className="text-xs text-slate-500">{k}</p><p className="mt-1 font-semibold">{v??"—"}{k==="Quantité"&&operations.section==="inventaires"?" %":""}</p></div>)}</div>}<DialogFooter><Button onClick={()=>setSelected(null)}>Fermer</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={formOpen} onOpenChange={setFormOpen}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{editing?`Modifier ${editing.id}`:operations.config.action}</DialogTitle><DialogDescription>Formulaire spécifique au module {operations.config.titre.toLowerCase()}.</DialogDescription></DialogHeader><StockOperationForm section={operations.section} values={form} productOptions={operations.productOptions} categoryOptions={operations.categoryOptions} onChange={(f,v)=>setForm(c=>({...c,[f]:v}))}/><DialogFooter><Button variant="ghost" onClick={()=>setFormOpen(false)}>Annuler</Button><Button onClick={submit}>{editing?"Enregistrer":"Créer"}</Button></DialogFooter></DialogContent></Dialog>
  <div className="flex flex-col gap-6"><header className="border-b-2 border-emerald-900 pb-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-emerald-800">Responsable Stock</p><h1 className="mt-2 text-2xl font-semibold text-slate-950">{operations.config.titre}</h1><p className="mt-2 text-sm text-slate-500">{operations.config.description}</p></div>{operations.config.action&&<Button onClick={create}><Plus className="size-4"/>{operations.config.action}</Button>}</div></header><Card className="rounded-lg border-slate-300 shadow-none"><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><CardTitle>{operations.section==="mouvements"?"Journal des mouvements":operations.section==="receptions"?"Contrôle des arrivages":operations.section==="inventaires"?"Campagnes de comptage":operations.section==="livraisons"?"Suivi des expéditions":"Registre opérationnel"}</CardTitle><div className="flex gap-2"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><Input className="pl-9" value={operations.search} onChange={e=>operations.setSearch(e.target.value)} placeholder="Rechercher…"/></div><select className="rounded-md border bg-white px-3 text-sm" value={operations.agency} onChange={e=>operations.setAgency(e.target.value)}><option>Toutes</option><option>Casablanca</option><option>Marrakech</option></select><Button variant="ghost" size="sm" onClick={operations.reset}><RotateCcw className="size-4"/></Button></div></div></CardHeader><CardContent><DataTable columns={columns} data={operations.items} emptyMessage="Aucun élément trouvé."/></CardContent></Card></div>
 </>;
}
