import { useState } from "react";
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertTriangle, ArrowDownToLine, ArrowRight, ArrowUpFromLine, Boxes, CheckCircle2, PackageCheck, PackageOpen, Truck, XCircle } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/Components/UI/Card";
import { Badge } from "@/Components/UI/Badge";
import { Button } from "@/Components/UI/Button";
import { Input } from "@/Components/UI/Input";
import { DataTable } from "@/Components/UI/DataTable";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/Components/UI/Dialog";
import { useToast } from "@/Components/UI/Toast";

const icons=[Boxes,AlertTriangle,Truck,CheckCircle2,PackageOpen,PackageCheck];
const tones={blue:"bg-blue-50 text-blue-700",emerald:"bg-emerald-50 text-emerald-700",amber:"bg-amber-50 text-amber-700",red:"bg-red-50 text-red-700",violet:"bg-violet-50 text-violet-700",cyan:"bg-cyan-50 text-cyan-700"};

export default function StockWorkspace({dashboard}) {
    const toast=useToast();
    const [alert,setAlert]=useState(null);
    const [reception,setReception]=useState(null);
    const [movementOpen,setMovementOpen]=useState(false);
    const [movement,setMovement]=useState({type:"Entrée",quantity:"",product:"",agency:"Casablanca"});
    const productOptions=dashboard.products||[];
    const submitMovement=()=>{if(!movement.product.trim()||Number(movement.quantity)<=0)return toast("Renseignez un produit et une quantité valide.","error");dashboard.addMovement(movement);toast(`${movement.type} enregistrée avec succès.`);setMovement({type:"Entrée",quantity:"",product:"",agency:"Casablanca"});setMovementOpen(false)};
    const columns=[
        {header:"Référence",accessorKey:"id",className:"font-semibold"},{header:"Produit",cell:r=><div><p className="font-medium">{r.product}</p><p className="text-xs text-slate-500">{r.category}</p></div>},{header:"Agence",accessorKey:"agency"},
        {header:"Disponible",cell:r=><span className={r.available===0?"font-bold text-red-600":"font-bold text-amber-600"}>{r.available}</span>},{header:"Réservé",accessorKey:"reserved"},{header:"Seuil",accessorKey:"threshold"},
        {header:"Statut",cell:r=><Badge variant={r.status==="Rupture"?"destructive":"warning"}>{r.status}</Badge>},{header:"Impact",accessorKey:"impact"},{header:"Action",cell:r=><Button size="sm" variant="outline" onClick={()=>setAlert(r)}>Traiter <ArrowRight className="size-3.5"/></Button>}
    ];
    return <div className="flex flex-col gap-6">
<Dialog open={movementOpen} onOpenChange={setMovementOpen}><DialogContent><DialogHeader><DialogTitle>Nouveau mouvement de stock</DialogTitle><DialogDescription>Enregistrez une entrée ou une sortie dans le journal.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Type<select value={movement.type} onChange={e=>setMovement({...movement,type:e.target.value})} className="mt-2 h-10 w-full rounded-md border px-3"><option>Entrée</option><option>Sortie</option></select></label><label className="text-sm font-medium">Agence<select value={movement.agency} onChange={e=>setMovement({...movement,agency:e.target.value})} className="mt-2 h-10 w-full rounded-md border px-3"><option>Casablanca</option><option>Marrakech</option></select></label><label className="text-sm font-medium sm:col-span-2">Produit<select className="mt-2 h-10 w-full rounded-md border border-slate-200 bg-white px-3" value={movement.product} onChange={e=>setMovement({...movement,product:e.target.value})}><option value="">Sélectionner un produit</option>{productOptions.map(product=><option key={product.id} value={product.name}>{product.name}</option>)}</select></label><label className="text-sm font-medium">Quantité<Input className="mt-2" type="number" min="1" value={movement.quantity} onChange={e=>setMovement({...movement,quantity:e.target.value})}/></label></div><DialogFooter><Button variant="ghost" onClick={()=>setMovementOpen(false)}>Annuler</Button><Button onClick={submitMovement}>Enregistrer le mouvement</Button></DialogFooter></DialogContent></Dialog>
        <Dialog open={Boolean(alert)} onOpenChange={open=>!open&&setAlert(null)}><DialogContent><DialogHeader><DialogTitle>Traiter l’alerte {alert?.id}</DialogTitle><DialogDescription>{alert?.product} · {alert?.agency}</DialogDescription></DialogHeader>{alert&&<div className="rounded-xl bg-red-50 p-4 text-sm text-red-800"><p><strong>{alert.available}</strong> disponible(s), <strong>{alert.reserved}</strong> réservé(s), seuil minimum <strong>{alert.threshold}</strong>.</p><p className="mt-2">Impact : {alert.impact}. Le Responsable Commercial concerné sera informé automatiquement.</p></div>}<DialogFooter><Button variant="ghost" onClick={()=>setAlert(null)}>Annuler</Button><Button onClick={()=>{dashboard.resolveAlert(alert.id);toast("Alerte traitée et Responsable Commercial informé automatiquement.");setAlert(null)}}>Informer et traiter</Button></DialogFooter></DialogContent></Dialog>
        <Dialog open={Boolean(reception)} onOpenChange={open=>!open&&setReception(null)}><DialogContent><DialogHeader><DialogTitle>Contrôle de réception</DialogTitle><DialogDescription>{reception?.id} · {reception?.supplier}</DialogDescription></DialogHeader>{reception&&<div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Agence</p><p className="font-semibold">{reception.agency}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Contenu</p><p className="font-semibold">{reception.items}</p></div></div>}<DialogFooter><Button variant="ghost" onClick={()=>setReception(null)}>Annuler</Button><Button onClick={()=>{dashboard.validateReception(reception.id);toast(`Réception validée. Les utilisateurs concernés sont informés de l’arrivée à ${reception.agency}.`);setReception(null)}}><CheckCircle2 className="size-4"/>Valider et informer</Button></DialogFooter></DialogContent></Dialog>
        <section className="border-b-2 border-emerald-900 pb-5"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-emerald-800">Stock · Console logistique</p><h1 className="mt-2 text-2xl font-semibold tracking-tight text-slate-950">Flux physiques et disponibilité</h1><p className="mt-2 text-sm text-slate-500">Casablanca + Marrakech · Synchronisation simulée à l’instant</p></div><div className="flex gap-2"><select value={dashboard.agency} onChange={e=>dashboard.setAgency(e.target.value)} className="rounded-md border border-slate-300 bg-white px-3 text-sm"><option>Toutes</option><option>Casablanca</option><option>Marrakech</option></select><Button onClick={()=>setMovementOpen(true)}>Nouveau mouvement</Button></div></div></section>
        <section className="overflow-hidden rounded-lg border border-slate-300 bg-white"><div className="grid divide-y divide-slate-200 sm:grid-cols-2 sm:divide-x sm:divide-y-0 xl:grid-cols-6">{dashboard.stats.map((item,i)=>{const Icon=icons[i];return <div key={item.id} className="min-w-0 p-4"><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{item.label}</span><Icon className="size-4 text-emerald-800"/></div><p className="mt-3 font-mono text-2xl font-semibold tabular-nums text-slate-950">{item.value}</p><p className="mt-1 truncate text-xs text-slate-500">{item.detail}</p></div>})}</div></section>
        <div className="grid gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader><CardTitle>Mouvements des 6 derniers jours</CardTitle></CardHeader><CardContent><div className="h-64"><ResponsiveContainer><AreaChart data={dashboard.trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day"/><YAxis/><Tooltip/><Area dataKey="entrees" name="Entrées" stroke="#10b981" fill="#d1fae5"/><Area dataKey="sorties" name="Sorties" stroke="#f59e0b" fill="transparent"/></AreaChart></ResponsiveContainer></div></CardContent></Card><Card><CardHeader><CardTitle>Santé globale du stock</CardTitle></CardHeader><CardContent><div className="h-64"><ResponsiveContainer><PieChart><Pie data={dashboard.health} dataKey="value" nameKey="label" innerRadius={58} outerRadius={85}>{dashboard.health.map(e=><Cell key={e.label} fill={e.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div></CardContent></Card></div>
        <Card className="rounded-lg border-slate-300 shadow-none"><CardHeader><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-red-700">Exceptions opérationnelles</p><CardTitle className="mt-1">Alertes nécessitant une action</CardTitle><p className="mt-1 text-sm text-slate-500">Filtrées selon l’agence sélectionnée</p></div><Badge variant="destructive">{dashboard.alerts.length} alertes</Badge></div></CardHeader><CardContent><DataTable columns={columns} data={dashboard.alerts} emptyMessage="Aucune alerte pour cette agence."/></CardContent></Card>
        <div className="grid gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader><CardTitle>Réceptions à contrôler</CardTitle></CardHeader><CardContent><div className="flex flex-col gap-3">{dashboard.receptions.map(r=><div key={r.id} className="flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center"><PackageCheck className="size-5 text-violet-600"/><div className="flex-1"><p className="font-semibold">{r.id} · {r.supplier}</p><p className="text-sm text-slate-500">{r.agency} · {r.items}</p></div><Badge variant={r.status==="Validée"?"success":"warning"}>{r.status}</Badge><Button size="sm" disabled={["Validée","En transit"].includes(r.status)} onClick={()=>setReception(r)}>{r.status==="Validée"?"Validée":r.status==="En transit"?"En transit":"Contrôler"}</Button></div>)}</div></CardContent></Card></div>
        <div className="grid gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader><CardTitle>Journal des mouvements</CardTitle></CardHeader><CardContent><div className="flex flex-col gap-4">{dashboard.activity.map(a=><div key={a.id} className="flex items-center gap-3"><div className={`flex size-9 items-center justify-center rounded-xl ${a.tone==="success"?"bg-emerald-50 text-emerald-600":a.tone==="danger"?"bg-red-50 text-red-600":"bg-amber-50 text-amber-600"}`}>{a.type==="Entrée"?<ArrowDownToLine className="size-4"/>:<ArrowUpFromLine className="size-4"/>}</div><div className="flex-1"><p className="text-sm font-semibold">{a.type}</p><p className="text-sm text-slate-500">{a.text}</p></div><p className="text-xs text-slate-400">{a.time}</p></div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>Actions rapides</CardTitle></CardHeader><CardContent><div className="grid gap-3"><Button variant="outline" onClick={()=>{setMovement({...movement,type:"Entrée"});setMovementOpen(true)}}><ArrowDownToLine className="size-4"/>Enregistrer une entrée</Button><Button variant="outline" onClick={()=>{setMovement({...movement,type:"Sortie"});setMovementOpen(true)}}><ArrowUpFromLine className="size-4"/>Enregistrer une sortie</Button><Button variant="ghost" onClick={()=>{dashboard.resetDashboard();toast("Données de démonstration réinitialisées.","info")}}>Réinitialiser la démonstration</Button></div></CardContent></Card></div>
    </div>;
}
